### ISSUE TITLE
Help! Black men invasion in game and IUMT does NOT function well!

### ISSUE THREAD

**Issue by AggelosAst** [Deniied0/IUMT#2]
I need IMMEDIATE assistant! Ive put IUMT in development production and im getting an exceesive amount of black people in game and IUMT does not seem like it can eliminate them therefore i am in a very menancing situation! Am i doing something wrong? I placed the scripts in the right places.

Thank you.
Mahmoud Abbas , مَحْمُود عَبَّاس.
**President of the State of Palestine and the Palestinian National Authority (PNA).**

**Comment by t0int1337** [comment]
Hi mahmoud abbas, im having this issue too. I also need this working for Xinjiang region.

**Comment by liverfail** [comment]
Hello, this tool does not remove players, it is for tracking Israeli players for intelligence monitoring.

Also, Israelis are not "black people", you may be referring to the Israelites/Hebrews which have all been kicked to Ethiopia due to Ashkenazi-Jewish white supremecy, more info here; https://www.youtube.com/watch?v=3bLNKyCN7Gs

Please stop trolling in github issues now.
